version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:15.2-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./postgres/.env.prod

  backend:
    container_name: backend
    image: backend:custom
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    expose:
      - 8000
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    env_file:
      - ./backend/.env.prod
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000 -w 2
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    image: frontend:custom
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    expose:
      - 3000
    env_file:
      - ./frontend/.env.prod
    command: serve -s /usr/src/app/build -l 3000
    depends_on:
      - backend

  nginx:
    container_name: nginx
    image: nginx:custom
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend

volumes:
  postgres:
    external: true
  static:
    external: false
  media:
    external: true