# pull official base image
FROM python:3.11-slim-buster

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
COPY ./requirements .
RUN pip install --no-cache --upgrade pip
RUN pip install --no-cache -r requirements/production.txt
RUN pip install --no-cache gunicorn

# copy django project
COPY . .
COPY .env.prod ./server

# run entrypoint.sh
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]