# Generated by Django 4.1.7 on 2023-03-07 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("register", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("summary", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="attachments/issues/",
                        validators=[projects.validators.validate_file_size],
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Task", "Task"), ("Bug", "Bug"), ("Story", "Story")],
                        default="Task",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Backlog", "Backlog"),
                            ("Selected For development", "Selected For development"),
                            ("InProgress", "InProgress"),
                            ("Done", "Done"),
                        ],
                        default="Backlog",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Highest", "Highest"),
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                            ("Lowest", "Lowest"),
                        ],
                        default="Medium",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ManyToManyField(
                        related_name="issues_assigned", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["project", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorkLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_spent",
                    models.DecimalField(
                        decimal_places=2,
                        error_messages={
                            "time_spent": "Duration Field Format is not correct"
                        },
                        max_digits=6,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worklogs",
                        to="projects.issue",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["issue", "time_spent"],
            },
        ),
        migrations.CreateModel(
            name="Watcher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchers",
                        to="projects.issue",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watched_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user", "issue"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, verbose_name="shortcut")),
                ("description", models.TextField()),
                (
                    "project_category",
                    models.CharField(
                        choices=[
                            ("Software", "Software"),
                            ("Marketing", "Marketing"),
                            ("Business", "Business"),
                        ],
                        default="Software",
                        max_length=50,
                    ),
                ),
                ("assignee", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                (
                    "company",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="register.company",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "company"],
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.project"
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues_reported",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="projects.issue"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["body", "user"],
            },
        ),
    ]
