# Generated by Django 4.1.7 on 2023-03-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=80)),
                ("email", models.EmailField(max_length=254)),
                ("city", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Companies",
                "ordering": ("company_name",),
            },
        ),
    ]
